<table align="left" width=100%>
    <tr>
        <td width="20%">
            <img src="GL-2.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Inclass - Lab <br> (Day 1) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#For Loop)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [1]:
import numpy as np
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
print(np.array(list_temperature))

[3.04 1.65 5.76 1.66 1.54 4.69 2.68]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [10]:
weights = [74.2,85,74,67.9,52,70.5,86,51.8,64,82]
w=np.array(weights)
w[w>68]

array([74.2, 85. , 74. , 70.5, 86. , 82. ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [23]:
print(np.random.randint(20,40,10))

[30 28 24 39 36 24 35 31 31 21]


In [24]:
np.random.seed(10)
print(np.random.randint(20,40,10))

[29 24 35 20 37 36 37 28 29 20]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [4]:
a=np.array([1,2,3,4,5])
print(np.power(a,5))

[   1   32  243 1024 3125]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [12]:
bb=np.arange(50,100,1)
bb[bb%2==1]

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [21]:
A=np.array([[1, 4, 8], [5, 7, 3], [9, 14, 2]])
np.sum(A,axis=0)

array([15, 25, 13])

In [3]:
A=np.array([[1, 4, 8], [5, 7, 3], [9, 14, 2]])
B=A.T
print(B)
for i in B:
    print(np.sum(i))

[[ 1  5  9]
 [ 4  7 14]
 [ 8  3  2]]
15
25
13


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [20]:
num=np.array([42, 87, 90, 14, 32, 75, 61, 80, 92])
for i in num:
    print(np.remainder(i,8))

2
7
2
6
0
3
5
0
4


<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [6]:
C=np.arange(1,21,1)
C.resize(2,10)
C[1,:5]

array([11, 12, 13, 14, 15])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [37]:
prices_monday =np.array([10, 30, 50, 60, 90])
prices_tuesday = np.array([50, 20, 80, 125, 10, 70])
np.intersect1d(prices_monday,prices_tuesday)

array([10, 50])

In [31]:
prices_monday =np.array([10, 30, 50, 60, 90])
prices_tuesday = np.array([50, 20, 80, 125, 10, 70])
for i in prices_monday:
    for j in prices_tuesday:
        if i in prices_tuesday:
            print(i)
        break

10
50


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [34]:
weights = np.array([57, 69, 54, 65 ,71, 62, 56])
heights = np.array([1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53])
k=0
for i in weights:
    bmi=i/(heights[k]**2)
    k+=1
    print(f"Bmi is {bmi}")

Bmi is 22.54657648036074
Bmi is 22.53061224489796
Bmi is 19.5964581216432
Bmi is 21.469150482230148
Bmi is 26.397977394408095
Bmi is 20.9572742022715
Bmi is 23.92242299970097


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [7]:
array1 = np.array([[3, 4], [8, 2],[5, 9]])
array2=np.array([[5,7]])
new_array1= np.append(array1,array2,axis=0)
new_array1

array([[3, 4],
       [8, 2],
       [5, 9],
       [5, 7]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [47]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [51]:
M =np.array([[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]])
print(M,'\n')
print(M.T)

[[15 17 45 56]
 [ 7 42 15 63]
 [54  3 61 41]
 [ 0 87 16 20]] 

[[15  7 54  0]
 [17 42  3 87]
 [45 15 61 16]
 [56 63 41 20]]


In [3]:
M =np.array([[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]])
result=np.zeros([4,4])
for i in range(len(M)):
    for j in range(len(M[0])):
        result[j][i]=M[i][j]
result

array([[15.,  7., 54.,  0.],
       [17., 42.,  3., 87.],
       [45., 15., 61., 16.],
       [56., 63., 41., 20.]])

<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [55]:
A1 = np.array([[5, 9], [7, 6]])
A2 = np.array([[8,-7], [0,4]])
np.vstack((A1,A2))

array([[ 5,  9],
       [ 7,  6],
       [ 8, -7],
       [ 0,  4]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [56]:
A1 = np.array([[5, 9], [7, 6]])
A2 = np.array([[8,-7], [0,4]])
np.hstack((A1,A2))

array([[ 5,  9,  8, -7],
       [ 7,  6,  0,  4]])

<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [8]:
A =np.array([[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]])
print(A,'\n\n')
np.vsplit(A,3)

[[ 4  7]
 [ 2 -3]
 [ 8  1]
 [ 0  9]
 [ 5 -1]
 [ 8  3]] 




[array([[ 4,  7],
        [ 2, -3]]),
 array([[8, 1],
        [0, 9]]),
 array([[ 5, -1],
        [ 8,  3]])]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [84]:
B = np.array([[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]])
print(B)
np.hsplit(B,2)

[[ 8  7  0  9]
 [ 2 -3  5 10]
 [ 8  5 -1  3]]


[array([[ 8,  7],
        [ 2, -3],
        [ 8,  5]]),
 array([[ 0,  9],
        [ 5, 10],
        [-1,  3]])]

<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [88]:
L1 = np.array([45, 67, 56, 71, 54, 62, 56])
L2 = np.array([21, 52, 64, 10, 49, 74, 26])
for i,j in zip(L1,L2):
    print([i,j])

[45, 21]
[67, 52]
[56, 64]
[71, 10]
[54, 49]
[62, 74]
[56, 26]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [91]:
numbers = np.array([6, 5, 3, 15])
for x in numbers:
    f=(2*x-1)/(x+5)
    print(f)

1.0
0.9
0.625
1.45
